### ISSUE TITLE
User can still view/edit their own decks when logged out

### ISSUE THREAD

**Issue by skeet70** [ebuchmann/duelyst.cards#11]
If a user tries to access their decks page and isn't logged in they should be taken to a login page.

**Comment by ebuchmann** [comment]
I purposfully left it public. Though, any editing capabilities should be disabled. I believe the current version has an issue where the textfield for the name can be edited (the server rejects it because they aren't logged in). I did fix this, but never published the changes.

**Comment by ebuchmann** [comment]
Fixed the issue where it showed the ability to edit a deck name while not logged in / not viewing your own deck.

A feature where on an account level the user can decide if their decks are public / private would be better.

**Comment by skeet70** [comment]
Created #13, I'll close this one since you got it.
